config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create]

  get 'login', to: 'sessions#new'

  post 'login', to: 'sessions#create'

  get 'welcome', to: 'sessions#welcome'

  get 'authorized', to: 'sessions#page_requires_login'
  
  resources :reports
  resources :teachers
  resources :exams
  resources :students
  root 'sessions#new'
  get 'users/index'
  get 'beranda/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
end

app/models/books2.rb
class Books2 < ApplicationRecord
end

app/models/exam.rb
class Exam < ApplicationRecord
end

app/models/report.rb
class Report < ApplicationRecord
end

app/models/student.rb
class Student < ApplicationRecord
end

app/models/teacher.rb
class Teacher < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
end

app/controllers/beranda_controller.rb
class BerandaController < ApplicationController
  def index
  end
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
  def new #untuk menampilkan form data baru
    @exam = Exam.new
    end
    
    def create #untuk memproses data baru yamg dimasukan di form new
    exam = Exam.new(resource_params)
    exam.save
    flash[:notice] = 'Book has been created'
    redirect_to exams_path
    end
    
    def edit #menampilkan data yang sudah disimpan di edit
    @exam = Exam.find(params[:id])
    end
    
    def update #melakukan proses ketika user mengedit data
    @exam = Exam.find(params[:id])
    @exam.update(resource_params)
    flash[:notice] = 'Book has been update'
    redirect_to exams_path(@exam)
    end
    
    def destroy #untuk menghapus data
    @exam = Exam.find(params[:id])
    @exam.destroy
    flash[:notice] = 'Book has been slain'
    redirect_to exams_path
    end
    
    def index #menampilkan seluruh data yang ada di database
    @exams = Exam.all
    end
    
    def show #menampilkan sebuah data secara detail
    id = params[:id]
    @exam = Exam.find(id)
    end
    
    private
    def resource_params
    params.require(:exam).permit( :title, :mapel, :duration,:nilai, :status,id_student)
    end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def new #untuk menampilkan form data baru
    @report = Report.new
    end
    
    def create #untuk memproses data baru yamg dimasukan di form new
    report = Report.new(resource_params)
    report.save
    flash[:notice] = 'Book has been created'
    redirect_to reports_path
    end
    
    def edit #menampilkan data yang sudah disimpan di edit
    @report = Report.find(params[:id])
    end
    
    def update #melakukan proses ketika user mengedit data
    @report = Report.find(params[:id])
    @report.update(resource_params)
    flash[:notice] = 'Book has been update'
    redirect_to reports_path(@report)
    end
    
    def destroy #untuk menghapus data
    @report = Report.find(params[:id])
    @report.destroy
    flash[:notice] = 'Book has been slain'
    redirect_to reports_path
    end
    
    def index #menampilkan seluruh data yang ada di database
    @reports = Report.all
    end
    
    def show #menampilkan sebuah data secara detail
    id = params[:id]
    @report = Report.find(id)
    end
    
    private
    def resource_params
    params.require(:report).permit( :title, :hasil, :mapel, :teacher_id, :student_id, :date)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authorized, only: [:new, :create, :welcome]

  def new
    @user = User.new
  end

  def create
    @user = User.find_by(username: params[:username]) 
      if @user && @user.authenticate(params[:password])      
        session[:user_id] = @user.id      
        redirect_to '/welcome'  
         else
        redirect_to '/login'   
      end
  end

  def login
  end

  def welcome
  end
  
  def page_requires_login
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
    def new #untuk menampilkan form data baru
    @student = Student.new
    end
    
    def create #untuk memproses data baru yamg dimasukan di form new
    student = Student.new(resource_params)
    student.save
    flash[:notice] = 'Book has been created'
    redirect_to students_path
    end
    
    def edit #menampilkan data yang sudah disimpan di edit
    @student = Student.find(params[:id])
    end
    
    def update #melakukan proses ketika user mengedit data
    @student = Student.find(params[:id])
    @student.update(resource_params)
    flash[:notice] = 'Book has been update'
    redirect_to students_path(@student)
    end
    
    def destroy #untuk menghapus data
    @student = Student.find(params[:id])
    @student.destroy
    flash[:notice] = 'Book has been slain'
    redirect_to students_path
    end
    
    def index #menampilkan seluruh data yang ada di database
    @students = Student.all
    end
    
    def show #menampilkan sebuah data secara detail
    id = params[:id]
    @student = Student.find(id)
    end
    
    private
    def resource_params
    params.require(:student).permit( :name, :username, :age,:kelas, :address, :city, :NIK)
    end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
    def new #untuk menampilkan form data baru
    @teacher = Teacher.new
    end
    
    def create #untuk memproses data baru yamg dimasukan di form new
    teacher = Teacher.new(resource_params)
    teacher.save
    flash[:notice] = 'Book has been created'
    redirect_to teachers_path
    end
    
    def edit #menampilkan data yang sudah disimpan di edit
    @teacher = Teacher.find(params[:id])
    end
    
    def update #melakukan proses ketika user mengedit data
    @teacher = Teacher.find(params[:id])
    @teacher.update(resource_params)
    flash[:notice] = 'Book has been update'
    redirect_to teachers_path(@teacher)
    end
    
    def destroy #untuk menghapus data
    @teacher = Teacher.find(params[:id])
    @teacher.destroy
    flash[:notice] = 'Book has been slain'
    redirect_to teachers_path
    end
    
    def index #menampilkan seluruh data yang ada di database
    @teachers = Teacher.all
    end
    
    def show #menampilkan sebuah data secara detail
    id = params[:id]
    @teacher = Teacher.find(id)
    end
    
    private
    def resource_params
    params.require(:teacher).permit( :NIK, :name, :age,:kelas, :mapel)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authorized, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.create(params.require(:user).permit(:username,        
    :password))

    session[:user_id] = @user.id
    
    redirect_to '/welcome'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/beranda_helper.rb
module BerandaHelper
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/exams/edit.html.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" href="#">
      <div class="wrapper">
        <div class="neon-wrapper">
            <span class="txt" >Mukhlis Febriansyah</span>
            <span class="gradient"></span>
            <span class="dodge"></span>
        </div>
      </div>
    </a>

    <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      <a class="navbar-item">
        Beranda
      </a>

      <a class="navbar-item">
        Table Students
      </a>
    </div>

    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
          <div class="button is-danger is-outlined">
            <%= link_to 'New Exam', new_exam_path %>
          </div>
          <a class="button is-light">
            <strong>Mukhlis Febriansyah</strong>
          </a>
        </div>
      </div>
    </div>
  </div>
</nav>


<div class="container is-widescreen">
<%= form_for @exam do |f| %>
    <div class="field">
        <%= f.label :id_student, :class => 'label' %>
        <div class="control">
         <%= f.text_field :id_student , :class => 'input' %> </br>
        </div>
    </div>
    
    
    <div class="field">
        <%= f.label :title, :class => 'label' %>
        <div class="control">
         <%= f.text_field :title , :class => 'input' %> </br>
        </div>
    </div>

    <div class="field">
        <%= f.label :mapel, :class => 'label' %>
        <div class="control">
         <%= f.text_field :mapel , :class => 'input' %> </br>
        </div>
    </div>

    <div class="field">
        <%= f.label :duration, :class => 'label' %>
        <div class="control">
         <%= f.text_field :duration , :class => 'input' %> </br>
        </div>
    </div>

    <div class="field">
        <%= f.label :nilai, :class => 'label' %>
        <div class="control">
         <%= f.text_field :nilai , :class => 'input' %> </br>
        </div>
    </div>

    <div class="field">
        <%= f.label :status, :class => 'label' %>
        <div class="control">
         <%= f.text_field :status , :class => 'input' %> </br>
        </div>
    </div>
    
    <%= f.submit "update", :class => 'button is-danger is-outlined' %>
<% end %>
</div>

app/views/exams/index.html.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" href="#">
      <div class="wrapper">
        <div class="neon-wrapper">
            <span class="txt" >Mukhlis Febriansyah</span>
            <span class="gradient"></span>
            <span class="dodge"></span>
        </div>
      </div>
    </a>

    <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      <a class="navbar-item">
        Beranda
      </a>

      <a class="navbar-item">
        Table Exams
      </a>
    </div>

    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
          <div class="button is-danger is-outlined">
            <%= link_to 'New Exam', new_exam_path %>
          </div>
        </div>
      </div>
    </div>
  </div>
</nav>

<div class="container is-fluid">
<section class="hero is-primary">
  <div class="hero-b                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ody">
                                                                                                                                                                                                                                                                                                                                            <div class="container">
      <h1 class="title">
        Exam Table
      </h1>
      <h2 class="subtitle">
        Mukhlis Febriansyah
      </h2>
    </div>
  </div>
</section>
<section class="section table">
<div class="table-container">
<table class="table is-bordered is-striped is-narrow is-hoverable is-fullwidth">
  <thead>
      <tr>
          <th><abbr title="Nama Siswa">ID Student</abbr></th>
          <th><abbr title="Nama Siswa">Title</abbr></th>
          <th><abbr title="Username">Mapel</abbr></th>
          <th><abbr title="Age">Duration</abbr></th>
          <th><abbr title="Kelas">Nilai</abbr></th>
          <th><abbr title="Address">Status</abbr></th>
          <th colspan="3" style="text-align:center"><abbr title="Action">Action</abbr></th>
      </tr>
  </thead>
  <tbody>
  <% @exams.each do |exam| %>
      <tr>
      <td><%= exam.id_student %></td>
      <td><%= exam.title %></td>  
      <td><%= exam.mapel %></td>
      <td><%= exam.duration %></td>
      <td><%= exam.nilai %></td>
      <td><%= exam.status %></td>
      <td><%= link_to 'detail', exam_path(exam) %>  <td><%= link_to 'Edit', edit_exam_path(exam) %>  <td><%= link_to 'Delete', exam_path(exam), method: :delete, data:{confirm: 'Are you sure?'} %> </td>
      </tr>
      <% end %>
  </tbody>
</table>
</div>
</div>

</section>

app/views/exams/new.html.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
<div class="navbar-brand">
  <a class="navbar-item" href="#">
    <div class="wrapper">
      <div class="neon-wrapper">
          <span class="txt" >Mukhlis Febriansyah</span>
          <span class="gradient"></span>
          <span class="dodge"></span>
      </div>
    </div>
  </a>

  <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
    <span aria-hidden="true"></span>
    <span aria-hidden="true"></span>
    <span aria-hidden="true"></span>
  </a>
</div>

<div id="navbarBasicExample" class="navbar-menu">
  <div class="navbar-start">
    <a class="navbar-item">
      Beranda
    </a>

    <a class="navbar-item">
      Table Students
    </a>
  </div>

  <div class="navbar-end">
    <div class="navbar-item">
      <div class="buttons">
        <div class="button is-danger is-outlined">
          <%= link_to 'New Student', new_student_path %>
        </div>
        <a class="button is-light">
          <strong>Mukhlis Febriansyah</strong>
        </a>
      </div>
    </div>
  </div>
</div>
</nav>

<div class="container is-widescreen">
<section class="hero is-primary">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        Create Exam Form
      </h1>
      <h2 class="subtitle">
        Mukhlis Febriansyah
      </h2>
    </div>
  </div>
</section>
<%= form_for @exam do |f| %>
    <div class="field">
        <%= f.label :id_student, :class => 'label' %>
        <div class="control">
         <%= f.text_field :id_student , :class => 'input' %> </br>
        </div>
    </div>
    
    
    <div class="field">
        <%= f.label :title, :class => 'label' %>
        <div class="control">
         <%= f.text_field :title , :class => 'input' %> </br>
        </div>
    </div>

    <div class="field">
        <%= f.label :mapel, :class => 'label' %>
        <div class="control">
         <%= f.text_field :mapel , :class => 'input' %> </br>
        </div>
    </div>

    <div class="field">
        <%= f.label :duration, :class => 'label' %>
        <div class="control">
         <%= f.text_field :duration , :class => 'input' %> </br>
        </div>
    </div>

    <div class="field">
        <%= f.label :nilai, :class => 'label' %>
        <div class="control">
         <%= f.text_field :nilai , :class => 'input' %> </br>
        </div>
    </div>
    
    <div class="field">
        <%= f.label :status, :class => 'label' %>
        <div class="control">
         <%= f.text_field :status , :class => 'input' %> </br>
        </div>
    </div>
    
    <%= f.submit "Save", :class => 'button is-danger is-outlined' %>
<% end %>
</div>

app/views/exams/show.html.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" href="#">
      <div class="wrapper">
        <div class="neon-wrapper">
            <span class="txt" >Mukhlis Febriansyah</span>
            <span class="gradient"></span>
            <span class="dodge"></span>
        </div>
      </div>
    </a>

    <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      <a class="navbar-item">
        Beranda
      </a>

      <a class="navbar-item">
        Table Students
      </a>
    </div>

    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
          <div class="button is-danger is-outlined">
            <%= link_to 'New Student', new_student_path %>
          </div>
        </div>
      </div>
    </div>
  </div>
</nav>
<div class="container"> 
  <section class="hero is-primary">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        Show By Id Exam Table
      </h1>
      <h2 class="subtitle">
        Mukhlis Febriansyah
      </h2>
    </div>
  </div>
</section>
<div class="table-container">
  <table class="table is-bordered is-striped is-narrow is-hoverable is-fullwidth">
    <thead>
        <tr>
            <th><abbr title="Nama Siswa">ID Student</abbr></th>
            <th><abbr title="Username">Title</abbr></th>
            <th><abbr title="Age">Mapel</abbr></th>
            <th><abbr title="Kelas">Duration</abbr></th>
            <th><abbr title="Address">Nilai</abbr></th>
            <th><abbr title="City">Status</abbr></th>
        </tr>
    </thead>
    <tbody>
        <tr>
        <td><%= @exam.id_student %></td>  
        <td><%= @exam.title %></td>
        <td><%= @exam.mapel %></td>
        <td><%= @exam.duration %></td>
        <td><%= @exam.nilai %></td>
        <td><%= @exam.status %></td>
        </tr>
    </tbody>
  </table>
</div>
</div>

app/views/reports/index.html.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" href="#">
      <div class="wrapper">
        <div class="neon-wrapper">
            <span class="txt" >Mukhlis Febriansyah</span>
            <span class="gradient"></span>
            <span class="dodge"></span>
        </div>
      </div>
    </a>

    <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      <a class="navbar-item">
        Beranda
      </a>

      <a class="navbar-item">
        Table Exams
      </a>
    </div>

    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
          <div class="button is-danger is-outlined">
            <%= link_to 'New Report', new_report_path %>
          </div>
        </div>
      </div>
    </div>
  </div>
</nav>

<div class="container is-fluid">
<section class="hero is-primary">
  <div class="hero-b                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ody">
                                                                                                                                                                                                                                                                                                                                            <div class="container">
      <h1 class="title">
        Report Table
      </h1>
      <h2 class="subtitle">
        Mukhlis Febriansyah
      </h2>
    </div>
  </div>
</section>
<section class="section table">
<div class="table-container">
<table class="table is-bordered is-striped is-narrow is-hoverable is-fullwidth">
  <thead>
      <tr>
          <th><abbr title="Nama Siswa">ID Student</abbr></th>
          <th><abbr title="Nama Siswa">ID Teacher</abbr></th>
          <th><abbr title="Username">Title</abbr></th>
          <th><abbr title="Age">Hasil</abbr></th>
          <th><abbr title="Kelas">Mapel</abbr></th>
          <th><abbr title="Address">Date</abbr></th>
          <th colspan="3" style="text-align:center"><abbr title="Action">Action</abbr></th>
      </tr>
  </thead>
  <tbody>
  <% @reports.each do |report| %>
      <tr>
      <td><%= report.student_id %></td>
      <td><%= report.teacher_id %></td>  
      <td><%= report.title %></td>
      <td><%= report.hasil %></td>
      <td><%= report.mapel %></td>
      <td><%= report.date %></td>
      <td><%= link_to 'detail', report_path(report) %>  <td><%= link_to 'Edit', edit_report_path(report) %>  <td><%= link_to 'Delete', report_path(report), method: :delete, data:{confirm: 'Are you sure?'} %> </td>
      </tr>
      <% end %>
  </tbody>
</table>
</div>
</div>

</section>

app/views/reports/show.html.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" href="#">
      <div class="wrapper">
        <div class="neon-wrapper">
            <span class="txt" >Mukhlis Febriansyah</span>
            <span class="gradient"></span>
            <span class="dodge"></span>
        </div>
      </div>
    </a>

    <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      <a class="navbar-item">
        Beranda
      </a>

      <a class="navbar-item">
        Table Students
      </a>
    </div>

    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
          <div class="button is-danger is-outlined">
            <%= link_to 'New Student', new_student_path %>
          </div>
        </div>
      </div>
    </div>
  </div>
</nav>
<div class="container"> 
  <section class="hero is-primary">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        Show By Id Report Table
      </h1>
      <h2 class="subtitle">
        Mukhlis Febriansyah
      </h2>
    </div>
  </div>
</section>
<div class="table-container">
  <table class="table is-bordered is-striped is-narrow is-hoverable is-fullwidth">
    <thead>
        <tr>
            <th><abbr title="Nama Siswa">ID Student</abbr></th>
            <th><abbr title="Username">ID Teacher</abbr></th>
            <th><abbr title="Age">Title</abbr></th>
            <th><abbr title="Kelas">Hasil</abbr></th>
            <th><abbr title="Address">Mapel</abbr></th>
            <th><abbr title="City">Date</abbr></th>
        </tr>
    </thead>
    <tbody>
        <tr>
        <td><%= @report.student_id %></td>  
        <td><%= @report.teacher_id %></td>
        <td><%= @report.title %></td>
        <td><%= @report.hasil %></td>
        <td><%= @report.mapel %></td>
        <td><%= @report.date %></td>
        </tr>
    </tbody>
  </table>
</div>
</div>

app/views/students/index.html.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" href="#">
      <div class="wrapper">
        <div class="neon-wrapper">
            <span class="txt" >Mukhlis Febriansyah</span>
            <span class="gradient"></span>
            <span class="dodge"></span>
        </div>
      </div>
    </a>

    <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      <a class="navbar-item">
        Beranda
      </a>

      <a class="navbar-item">
        Table Students
      </a>
    </div>

    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
          <div class="button is-danger is-outlined">
            <%= link_to 'New Student', new_student_path %>
          </div>
          
        </div>
      </div>
    </div>
  </div>
</nav>

<div class="container is-fluid">
<section class="hero is-primary">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        Student Table
      </h1>
      <h2 class="subtitle">
        Mukhlis Febriansyah
      </h2>
    </div>
  </div>
</section>
<section class="section table">
<div class="table-container">
<table class="table is-bordered is-striped is-narrow is-hoverable is-fullwidth">
  <thead>
      <tr>
          <th><abbr title="Nama Siswa">Nama</abbr></th>
          <th><abbr title="Username">Username</abbr></th>
          <th><abbr title="Age">Age</abbr></th>
          <th><abbr title="Kelas">Kelas</abbr></th>
          <th><abbr title="Address">Address</abbr></th>
          <th><abbr title="City">City</abbr></th>
          <th><abbr title="NIK">NIK</abbr></th>
          <th colspan="3" style="text-align:center"><abbr title="Action">Action</abbr></th>
      </tr>
  </thead>
  <tbody>
  <% @students.each do |student| %>
      <tr>
      <td><%= student.name %></td>  
      <td><%= student.username %></td>
      <td><%= student.age %></td>
      <td><%= student.kelas %></td>
      <td><%= student.address %></td>
      <td><%= student.city %></td>
      <td><%= student.NIK %></td>
      <td><%= link_to 'detail', student_path(student) %>  <td><%= link_to 'Edit', edit_student_path(student) %>  <td><%= link_to 'Delete', student_path(student), method: :delete, data:{confirm: 'Are you sure?'} %> </td>
      </tr>
      <% end %>
  </tbody>
</table>
</div>
</div>

</section>

app/views/teachers/index.html.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" href="#">
      <div class="wrapper">
        <div class="neon-wrapper">
            <span class="txt" >Mukhlis Febriansyah</span>
            <span class="gradient"></span>
            <span class="dodge"></span>
        </div>
      </div>
    </a>

    <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      <a class="navbar-item">
        Beranda
      </a>

      <a class="navbar-item">
        Table Teachers
      </a>
    </div>

    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
          <div class="button is-danger is-outlined">
            <%= link_to 'New Teacher', new_teacher_path %>
          </div>
          
        </div>
      </div>
    </div>
  </div>
</nav>

<div class="container is-fluid">
<section class="hero is-primary">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        Student Table
      </h1>
      <h2 class="subtitle">
        Mukhlis Febriansyah
      </h2>
    </div>
  </div>
</section>
<section class="section table">
<div class="table-container">
<table class="table is-bordered is-striped is-narrow is-hoverable is-fullwidth">
  <thead>
      <tr>
          <th><abbr title="Nama Siswa">NIK</abbr></th>
          <th><abbr title="Username">Nama</abbr></th>
          <th><abbr title="Age">Age</abbr></th>
          <th><abbr title="Kelas">Kelas</abbr></th>
          <th><abbr title="Address">Mapel</abbr></th>
          <th colspan="3" style="text-align:center"><abbr title="Action">Action</abbr></th>
      </tr>
  </thead>
  <tbody>
  <% @teachers.each do |teacher| %>
      <tr>
      <td><%= teacher.NIK %></td>
      <td><%= teacher.name %></td>  
      <td><%= teacher.age %></td>
      <td><%= teacher.kelas %></td>
      <td><%= teacher.mapel %></td>
      <td><%= link_to 'detail', teacher_path(teacher) %>  <td><%= link_to 'Edit', edit_teacher_path(teacher) %>  <td><%= link_to 'Delete', teacher_path(teacher), method: :delete, data:{confirm: 'Are you sure?'} %> </td>
      </tr>
      <% end %>
  </tbody>
</table>
</div>
</div>

</section>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>